/**
 * The only place the app reads data.
 *
 * Today that means JSON generated by the Python pipeline (see
 * ingest/export_web.py) and read at build time. When Phase 3 needs arbitrary
 * tickers generated on demand, swapping to a database is confined to this
 * file — nothing else imports from `data/` directly.
 *
 * The important behaviour here is `attachCaveats`. Some figures are actively
 * misleading on their own rather than merely incomplete: Redwood's gross
 * debt-to-equity reads 29.86x when the company is liable for about 4.84x.
 * Rather than trusting every future page to remember the pairing, caveats are
 * bound to their KPI as the data loads, so a KPI that carries a warning
 * cannot be rendered without it.
 */

import fs from "node:fs";
import path from "node:path";

const DATA_DIR = path.join(process.cwd(), "data");

export type Point = { quarter: string; value: number };

export type Kpi = {
  label: string;
  available: boolean;
  unit?: string;
  quarters?: number;
  first?: string;
  latest?: string;
  latest_value?: number;
  note?: string;
  series?: Point[];
  reason?: string;
  /** Bound at load time — see attachCaveats. */
  caveats?: Caveat[];
};

export type Caveat = {
  kpi: string;
  companion?: string;
  headline: string;
  detail: string;
};

export type Signal = {
  date: string;
  item: string;
  meaning: string;
  severity: "high" | "medium";
  accession: string;
  url: string;
};

export type Company = {
  ticker: string;
  name: string;
  cik: string;
  tier: "curated" | "generic";
  kpis: Record<string, Kpi>;
  caveats: Caveat[];
  signals: Signal[];
};

export type IndexEntry = {
  ticker: string;
  name: string;
  tier: "curated" | "generic";
  latest_quarter: string | null;
  kpi_count: number;
  signal_count: number;
  caveat_count: number;
};

/**
 * Bind each caveat to the KPI it qualifies, so the two travel together.
 */
function attachCaveats(company: Company): Company {
  for (const caveat of company.caveats) {
    const kpi = company.kpis[caveat.kpi];
    if (!kpi) continue;
    kpi.caveats = [...(kpi.caveats ?? []), caveat];
  }
  return company;
}

export function getCompany(ticker: string): Company {
  const raw = fs.readFileSync(
    path.join(DATA_DIR, `${ticker.toLowerCase()}.json`),
    "utf8",
  );
  return attachCaveats(JSON.parse(raw) as Company);
}

export function getIndex(): IndexEntry[] {
  const raw = fs.readFileSync(path.join(DATA_DIR, "index.json"), "utf8");
  return JSON.parse(raw) as IndexEntry[];
}

export function getTickers(): string[] {
  return getIndex().map((entry) => entry.ticker.toLowerCase());
}

/** Format a value for display, given the unit its profile declared. */
export function formatValue(value: number | undefined, unit?: string): string {
  if (value === undefined || value === null) return "—";

  if (unit === "usd_per_share") {
    return `${value < 0 ? "−" : ""}$${Math.abs(value).toFixed(2)}`;
  }
  if (unit === "multiple") return `${value.toFixed(2)}×`;
  if (unit === "usd") {
    const abs = Math.abs(value);
    const sign = value < 0 ? "−" : "";
    if (abs >= 1e9) return `${sign}$${(abs / 1e9).toFixed(2)}B`;
    if (abs >= 1e6) return `${sign}$${(abs / 1e6).toFixed(1)}M`;
    return `${sign}$${abs.toLocaleString()}`;
  }
  return value.toLocaleString();
}

/** Percentage change between the last two quarters, or null if not meaningful. */
export function quarterChange(kpi: Kpi): number | null {
  const series = kpi.series;
  if (!series || series.length < 2) return null;

  const previous = series[series.length - 2].value;
  const current = series[series.length - 1].value;

  // A sign flip makes a percentage misleading rather than informative, and a
  // zero base makes it undefined.
  if (previous === 0) return null;
  if (previous < 0 !== current < 0) return null;

  return ((current - previous) / Math.abs(previous)) * 100;
}
