"""
Prove the extraction pipeline still produces the output it used to.

tests/fixtures/ holds twenty CSVs generated by code that was verified by hand:
segment contributions reconciled to consolidated net income to the dollar,
the recourse-debt components reconciled against an independently tagged
total, and headline figures cross-checked against the filings' own MD&A prose.

That makes them a golden dataset. Any refactor is only correct if it
reproduces them byte for byte - a diff means a judgment call was lost
somewhere in the generalisation, which is exactly the failure mode that
matters when the engine starts serving companies nobody has checked.

Run the extraction scripts first, then:

    python3 tests/check_regression.py

Regenerate the fixtures deliberately - never to make a failure go away - with:

    cp rwt_*.csv tests/fixtures/
    (cd tests/fixtures && shasum -a 256 *.csv > ../fixtures.sha256)
"""

import csv
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
FIXTURES = os.path.join(HERE, "fixtures")


def compare_files():
    """Byte-for-byte comparison of every fixture against its current file."""
    mismatches, missing = [], []

    for name in sorted(os.listdir(FIXTURES)):
        if not name.endswith(".csv"):
            continue
        current = os.path.join(REPO, name)
        if not os.path.exists(current):
            missing.append(name)
            continue
        with open(os.path.join(FIXTURES, name), "rb") as a, open(current, "rb") as b:
            if a.read() != b.read():
                mismatches.append(name)

    return mismatches, missing


def check_invariants():
    """Correctness properties that must hold regardless of the file contents.

    These catch a subtler failure than a diff: fixtures could be regenerated
    wholesale and still be wrong. These say what "right" means.
    """
    failures = []

    def path(name):
        return os.path.join(REPO, name)

    # Segment contributions must sum to consolidated net income exactly.
    rows = list(csv.DictReader(open(path("rwt_segment_quarterly.csv"))))
    consolidated = {
        r["quarter"]: float(r["net_income"])
        for r in csv.DictReader(open(path("rwt_quarterly_net_income_complete.csv")))
    }
    for quarter in sorted({r["quarter"] for r in rows}):
        total = sum(
            float(r["value"])
            for r in rows
            if r["quarter"] == quarter and r["line_item"] == "segment_contribution"
        )
        if total == 0 or quarter not in consolidated:
            continue  # quarter has no segment contributions reported
        if abs(total - consolidated[quarter]) > 0.5:
            failures.append(
                f"{quarter}: segments sum to {total:,.0f}, "
                f"consolidated net income is {consolidated[quarter]:,.0f}"
            )

    # Recourse debt components must add up to the reported total.
    for row in csv.DictReader(open(path("rwt_quarterly_recourse_leverage.csv"))):
        parts = float(row["secured_recourse_debt"]) + float(row["corporate_debt"])
        if abs(parts - float(row["total_recourse_debt"])) > 1:
            failures.append(f"{row['quarter']}: recourse components do not sum")

    # Operating expenses cannot be negative in reality.
    for row in csv.DictReader(open(path("rwt_quarterly_operating_expenses.csv"))):
        if float(row["operating_expenses"]) < 0:
            failures.append(f"{row['quarter']}: negative operating expenses")

    return failures


def main():
    mismatches, missing = compare_files()
    failures = check_invariants()

    total = len([n for n in os.listdir(FIXTURES) if n.endswith(".csv")])
    print(f"Comparing {total} fixtures against current output\n")

    if missing:
        print(f"  MISSING ({len(missing)}) - run the extraction scripts first:")
        for name in missing:
            print(f"    {name}")

    if mismatches:
        print(f"  CHANGED ({len(mismatches)}):")
        for name in mismatches:
            print(f"    {name}")
    elif not missing:
        print(f"  all {total} files byte-identical")

    print()
    if failures:
        print(f"  INVARIANTS FAILED ({len(failures)}):")
        for failure in failures:
            print(f"    {failure}")
    else:
        print("  all invariants hold")

    if mismatches or missing or failures:
        print("\nFAIL")
        return 1
    print("\nPASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
